### ISSUE TITLE
Resource for dual booting Windows and Ubuntu

### ISSUE THREAD

**Issue by rw2mitch** [brittAnderson/Intro2Computing4Psychology#1]
If you are looking to dual boot Windows and Ubuntu, here is a link to a page I found helpful: [Beginner's Guide To /install Windows 10 With Ubuntu in Dual Boot](https://itsfoss.com/install-ubuntu-1404-dual-boot-mode-windows-8-81-uefi/)

If anyone needs help, feel free to ask me questions!

**Comment by brittAnderson** [comment]
Thanks. Hope more folks will share links like this.
