### ISSUE TITLE
Learn Restrictions on Submitting sh files

### ISSUE THREAD

**Issue by MollyMatthews** [brittAnderson/Intro2Computing4Psychology#100]
Hi,
Has anyone been able to submit a .sh file to learn? (for the terminal assignment)
[https://brittanderson.github.io/Intro2Computing4Psychology/book/terminal.html](url)

Learn gives me this message when I try to submit the .sh file: 
![image](https://github.com/brittAnderson/Intro2Computing4Psychology/assets/133702252/731c0e37-c439-4a4e-87a6-160d3f75d0e2)

**Comment by brittAnderson** [comment]
You cannot submit an sh file on learn. They block executables. Just change the sh ending to txt and then I change them back after downloading.

**Comment by cmarfil7** [comment]
I was just about to post this issue, thank you for posting Molly!
