### ISSUE TITLE
Issue with terminal in VM

### ISSUE THREAD

**Issue by teeoladipo** [brittAnderson/Intro2Computing4Psychology#101]
I was trying to download psychopy using Homebrew on my VM. All of a sudden, the VM crashed and now I can't even type in the terminal, it won't allow me to. I'm using Windows 11 on a PC with Ubuntu installed.

**Comment by brittAnderson** [comment]
Homebrew is used for installing programs on a Mac OSX. You would install this not in your VM, but just on the Mac itself. But you said you were using Windows. So you installed a Mac program in a Linux VM on a Windows computer. I assume you will have to delete your Ubuntu VM and re-install it.

**Comment by teeoladipo** [comment]
In the notes, it says that is applicable for installing on a Windows 11 VM but maybe I didn't follow the right instructions. I'll just delete and re-install it then. Thank you!
