### ISSUE TITLE
Audio issues in Ubuntu (MAC)

### ISSUE THREAD

**Issue by ayoonaifo** [brittAnderson/Intro2Computing4Psychology#103]
The audio kept cutting out when trying to watch a video from LEARN in Ubuntu. To fix this, you can close Ubuntu, restart it, and in the top left of your MAC desktop you can go to Devices --> Audio ---> Audio Output (check that option) and it should be working again.

**Comment by brittAnderson** [comment]
Thank you for sharing your work around. You can of course watch the videos on the regular, non VM, side of the mac too.
