### ISSUE TITLE
failed to install psychopy by using Ubuntu version 20.04, 

### ISSUE THREAD

**Issue by a295chen** [brittAnderson/Intro2Computing4Psychology#104]
I tried to install Ubuntu version 22.04 LTS in the beginning. But it didn't work. (My laptop is Lenovo. After login into the account, the whole screen was blue, and nothing else content. So, I installed the Ubuntu 20.04. Does it have any other ways to install psychopy in Ubuntu 20.04?

**Comment by brittAnderson** [comment]
At this point I recommend following the same advice I gave for the owners of new macs. Do NOT use the VM to install psychopy, but install the standalone version on your NON-VM operating system. But make sure you use the coder and not builder functions. Here is the video for Mac owners, but most of it will apply to you too. https://vimeo.com/810622435
