### ISSUE TITLE
VM keeps crashing on MAC

### ISSUE THREAD

**Issue by ayoonaifo** [brittAnderson/Intro2Computing4Psychology#105]
Not sure if anyone else is experiencing this, but VM keeps opening for a while and crashing unexpectedly on my MacBook. I tried quitting VM and restarting my Mac but to no avail. What worked for me was actually deleting some files to create more space, then I updated & restarted the mac completely and got VM working fine again -- hope this helps!

**Comment by brittAnderson** [comment]
Thanks for the recommendation. In these days of cloud storage people can forget to pay attention to their local storage limits. This is especially true of using VMs which may have more resource constraints than we are used to.
