### ISSUE TITLE
Output Data Compiles Weird

### ISSUE THREAD

**Issue by MollyMatthews** [brittAnderson/Intro2Computing4Psychology#106]
Hello,
We have an experiment with two phases. One is a verb list phase and another is a noun list phase. We have successfully gotten the data from the key responses to fill in in an output spreadsheet, however since we are using "nextEntry", for the second phase the data is staggered and not in line with the first. I'll attach an example of what it looks like.
And this is a fragment of the code for the reaction time timer which we are adding to the output.
Does this make sense? Does anyone know how we can get our output data to fill in adjacent to each other for both phases?

`# Waiting for response, formatting string, writing to data file, creating timer
    timer = clock.Clock()
    rnR = event.waitKeys(keyList=['z','m'])
    react = timer.getTime()
    rnResp = rvR[0]
    exp.addData('RN_Resp',rvResp)
    exp.addData('RN_React',react)
    timer.reset(newT=0.0)
    exp.nextEntry()`

We also don't know how to get the headings to not keep repeating but that's a lesser issue.
[](url)
[data_IssueExample.csv](https://github.com/brittAnderson/Intro2Computing4Psychology/files/12187610/data_IssueExample.csv)

**Comment by brittAnderson** [comment]
Send me the .py script so I can see it all in context and try to run it locally.

**Comment by brittAnderson** [comment]
And maybe you just want to go more basic. Let's assume you have three variables you collect: rt, button, word. The first one is a float, second and third character strings. Then after you collect them, `rt = clock.getTime()` or whatever you add a line to your file with something like:
    
    outstring = str(rt) + "," + button + "," + word + "\n"
    f.write(outstring)

This is not "real" code. Just to give you an idea that you can avoid all the trial handler magic and just write your own data after each choice word is shown.
