### ISSUE TITLE
Xubuntu Installation Corruption File USB - PC/WIndows

### ISSUE THREAD

**Issue by hyacinthray** [brittAnderson/Intro2Computing4Psychology#11]
I am currently using a PC/Windows laptop and I have used Rufus on my USB. Mu USB is new and I bought it a couple of days ago. I have redownloaded Xubuntu three times and each time I try to open the program, it gives me an error and tells me that the file is corrupted. Anyone also got this problem? If so, does anyone know how to fix it? Thank you!

**Comment by s296ahme** [comment]
Hi @hyacinthray, I had the same problem!! If you look at issue #7 under closed issues, you can see the explanation that Dr. Anderson gave me. He provides a link that can help you "format" your USB which means to wipe the data on it. 

I personally continued to have problems even after formatting the USB, so I resorted to getting another USB, re-downloaded Rufus, followed the videos to the T and it was able to work.

Hope it works for you!

**Comment by brittAnderson** [comment]
This is a tricky process. It does work, but it is very unforgiving. Like @s296ahme says you need to follow the instructions to the T. I too have failed multiple times at this, but it gets easier with practice.
