### ISSUE TITLE
Trouble with Ubuntu Persistence on Mac

### ISSUE THREAD

**Issue by ClaireGrace** [brittAnderson/Intro2Computing4Psychology#12]
Hi, all, 
I have Linux installed on a USB but it has no persistence. I am unable to use mkusb: when I type in the code it says that the 'user or team does not exist'. Any ideas?
Claire

**Comment by w24cai** [comment]
I followed the instruction of mkusb posted in other threads and it worked out. Maybe you should post the screenshot of the message and the commands you typed in the terminal?

**Comment by ClaireGrace** [comment]
I figured it out! Just downloaded the memory stick on a Windows computer and it works.
