### ISSUE TITLE
Emacs "execute" command

### ISSUE THREAD

**Issue by kaitlingaerlan** [brittAnderson/Intro2Computing4Psychology#15]
To install a package using "use-package" in the emacs init file, what command is used to "execute" the code that installs the package?

**Comment by kegsss** [comment]
Hey Kaitlin, I'm trying to figure this out as well but can't see to find the execute command for that magit package block of code, I tried using this but not sure if it worked: https://jwiegley.github.io/use-package/installation/#post-installation-tasks

**Comment by kaitlingaerlan** [comment]
Hey @kegsss in the video about installing elpy, he mentions that you can execute while in the init.el file by using `C-x C-e` It worked for me this way!

**Comment by kegsss** [comment]
Thanks Kaitlin! That seemed to work, did you end up figuring out how to use it? I downloaded a zip of the repo here but I don't think magit will work like that, when I type C-c m when on the assessment line as in his video I can't seem to get the same information appear. Did you end up figuring out how to use this?

**Comment by kaitlingaerlan** [comment]
No not yet, but I feel like we'll eventually learn how to use it once we get to the lessons about git and version control.
