### ISSUE TITLE
Using the magit package

### ISSUE THREAD

**Issue by kaitlingaerlan** [brittAnderson/Intro2Computing4Psychology#16]
Hi,

I'm having trouble understanding the magit package and what it's supposed to do once it's installed. I wasn't able to access the repository for the course or even my own respository as shown in the video - is this something I should be able to do?

Thanks!

**Comment by brittAnderson** [comment]
The magit is what is called a "porcelain". If you think of git as the plumbing, this is the decorative visible part that is above ground. I find it more convenient to use if for repositories I have already cloned by other means, though there is the possibility of cloning within emacs. I found it easier to deal with my typos at the terminal than in magit. Once the repo exists than you C-x d to navigate to the directory where the repo exists, and at that point C-c C-m on most emacs installs will get you the magit list of options that you select via characters. 

So to clone the repos I recommend using your terminal and doing the copy and paste of the git clone address you find on github. Then if you find it convenient use magit. If not, don't. The real learning exercise with Magit is just how to install a package in emacs, and how to edit the init.el file.
