### ISSUE TITLE
Ubuntu and Xubuntu

### ISSUE THREAD

**Issue by w24cai** [brittAnderson/Intro2Computing4Psychology#18]
I am wondering if I can use Ubuntu instead of Xubuntu for the assessment?

**Comment by bmmunds** [comment]
Hi. In one of Dr. Anderson's videos he mentions that you can use Ubuntu but recommends XUbuntu if you are using a usb because it is a more condensed smaller version.

**Comment by brittAnderson** [comment]
If you have ubuntu working, that is great. Use it. I started with the idea of using ubuntu for the course, but it really bogged down on my USB practice runs so I switched to Xubuntu and that seemed to be more manageable. I have found the same thing when running on older computers too. But the two linux versions are largely the same for our purpose. And if you have ubuntu running, but want things to look like what other people are using you could explore installing the `xfce-desktop`. This might fill your USB and slow it down, I have not tested this, but then when you start up you should be able to select xfce which is what gives Xubuntu its name, and your desktop will look like the videos and have the same tools installed.
