### ISSUE TITLE
Requirement for Python For loop assignment

### ISSUE THREAD

**Issue by w24cai** [brittAnderson/Intro2Computing4Psychology#19]
I have a few questions about the requirement of this assignment.

1. Is there any requirement on the contract of the input variable for the defined function? Do we use Str or list?

2. How should the output printed look like? For example, if the word is "cba", should the out put printed in separated lines, and look like:
    c
    a
    The first letter of list one is c, and the first letter of the sorted list is a
    b
    b
    The second letter of list one is b, and the third letter of the sorted list is b
    a
    c
    The third letter of list one is c, and the third letter of the sorted list is c

3. Can I replace first, second, etc by number? For example, 1th, 2th, 3th. Or start with 0, like 0th, 1th, 2th.  

Thanks in advance!

**Comment by brittAnderson** [comment]
I intend to be pretty forgiving here. I want you to learn how to access the elements of a list without overwriting the original data, learn some things about sorting, and printing. So if your code does what I ask, but the formatting is different it should be not big deal. I want you to learn the substance of the assignment. Making it pretty (so-called pretty printing) is important to make code and output readable, but is not our focus at this state.
