### ISSUE TITLE
Typing in ubuntu- mac

### ISSUE THREAD

**Issue by skundurt** [brittAnderson/Intro2Computing4Psychology#21]
Hi, 

I'm using Ubuntu on a Mac and whenever I type the cursor jumps to the left of the screen, sometimes all the way up to the start of a document. This is significantly hindering my productivity on Ubuntu, I was wondering if anyone had the same issue, and if so, what helped?

Thanks

**Comment by s296ahme** [comment]
Hey! I'm having the same problem and I'm using PC. (it literally took me double the time to write this comment because the cursor jumps).

**Comment by kegsss** [comment]
Hey all, my guess is you might not have the proper driver installed for your trackpads for use in Xubuntu. Can you test this with an external mouse via USB to see if it still does it? I also found this discussion forum on the topic and one user suggested that installing xserver-xorg-input-libinput worked for him although supposedly it might have been an old Ubuntu bug, I’m not sure if it was ever patched in Xubuntu but I’d assume so?

**Comment by kegsss** [comment]
> Hey all, my guess is you might not have the proper driver installed for your trackpads for use in Xubuntu. Can you test this with an external mouse via USB to see if it still does it? I also found this discussion forum on the topic and one user suggested that installing xserver-xorg-input-libinput worked for him although supposedly it might have been an old Ubuntu bug, I’m not sure if it was ever patched in Xubuntu but I’d assume so? Here’s the link to the forum: https://askubuntu.com/questions/894679/ubuntu-touchpad-issues-mouse-pointer-jumps-around

Also - if the external mouse works, you can scroll down to one of the replies here to disable your trackpad within Xubuntu itself (don’t worry, this won’t affect your MacOS or WIN10 trackpad functionality): https://unix.stackexchange.com/questions/328538/cursor-moving-erratically-on-its-own

**Comment by brittAnderson** [comment]
I often disable the track pad if the computer has a touch screen for this reason ( and why I prefer lenovo thinkpads that have the little joystick in the middle). But @kegsss is right, I think. It is a problem for the drivers for the touch pad. Searching for xorg touchpad mac would be the best path. And while this is just annoying here the idea is that if you are using an eye tracker or an eeg machine or trying to set up a task with a joystick some experience with diagnosing and solving user interface problems will be very useful. And by the way I have had problems with each of those in the past. Will leave open for a while in case someone has a solution to post.
