### ISSUE TITLE
Asssesment for R - dist variable

### ISSUE THREAD

**Issue by hyacinthray** [brittAnderson/Intro2Computing4Psychology#28]
Hi all,

I just need clarification for the assessment for R, it tells us to sort the cars by the dist variable. Is that the dist function in R or are we trying to order by the distance of the cars? Thank you!

**Comment by kaitlingaerlan** [comment]
I'm pretty sure it's the second one - trying to order by the distance of the cars, because he also says "sort"! :)

**Comment by brittAnderson** [comment]
yes, if you look at `names(cars)` you will see the names of all the columns. One of them is dist which is short for distance. That is the "column" you are sorting and doing some basic inspection of. At this point your model of the cars dataframe as an excel spreadhsheet will get you pretty far. But while that is a fine analogy for starters the R dataframe can do so much more (and [excel maybe not so much](https://uk.finance.yahoo.com/news/missing-coronavirus-tests-glitch-large-excel-spreadsheet-file-095054235.html?guccounter=1&guce_referrer=aHR0cHM6Ly9kdWNrZHVja2dvLmNvbS8&guce_referrer_sig=AQAAAHyQRjxzrKAllUR135B4ApGS1sleaZoiedaX9Nh51zoIlll_j1g2nfqxK3GQvZ6lqe6_tVXm1_UQTfnpk_bzN9S14hiBkKOObg9UB3o5xzeW0DfixKvzurwqvDGh5mORJ7K2Y7l7TL5ej8aR0c62KamBgXNQg9r8CpSsikc889Dv)).
