### ISSUE TITLE
Sarah Naseem 

### ISSUE THREAD

**Issue by s3naseem** [brittAnderson/Intro2Computing4Psychology#29]
Issue created for assessment.

**Comment by bmmunds** [comment]
Hey Sarah, 
This part of the assignment is meant to be done on 'psych363practice'. I am not sure if Dr. Anderson will accept it for marks here or not. Hope this helps!

**Comment by s3naseem** [comment]
Oh! I didn't realize I created an issue in the wrong repository. Thank you for telling me.
