### ISSUE TITLE
htmlize not on my list on emacs

### ISSUE THREAD

**Issue by ClaireGrace** [brittAnderson/Intro2Computing4Psychology#30]
Hi, all! I am trying to convert my .org files to an html and I am told I need htmlize. I tried following Dr. Anderson's video instructions, but htmlize does not come as a package available to install. What should I do?

**Comment by brittAnderson** [comment]
A much longer action can be found [here](http://ergoemacs.org/emacs/emacs_package_system.htmll). Basically, do `M-x package-list-packages` find htmlize, mark with `i`, then execute with `x`. and you should have the package installed.

**Comment by brittAnderson** [comment]
P.S. if this solutions works for you, or you find another, please post it here then close the issue. If it doesn't work, then just add to the issue.

**Comment by s296ahme** [comment]
Hey! Maybe you could also try doing a `sudo apt update` in the terminal just in case. I find that when I do that before downloading anything new, it seems everything is there like the videos.

**Comment by ClaireGrace** [comment]
Hi, there! The first thing I tried were Dr. Anderson's instructions, which did not work, which is the reason I raised this issue. Sudo apt update also did not work. Any other ideas? There is also a LEARN thread about this.

**Comment by brittAnderson** [comment]
Taking this up on line but off github.
