### ISSUE TITLE
Github pull assessment - 'gitnames'

### ISSUE THREAD

**Issue by skundurt** [brittAnderson/Intro2Computing4Psychology#31]
![Screenshot_2020-10-24_16-02-04](https://user-images.githubusercontent.com/70975478/97092611-4ef80980-1613-11eb-8afe-ab12aae597a0.png)

I'm stuck at the 'cd gitnames/' command as it says no such file or directory exists. I was wondering if anyone else had this issue?

**Comment by skundurt** [comment]
Update: I had to refork the britt anderson psych363 repository, possibly because the 'gitnames' file was not added to this repository when I first forked it. Knowing this would have saved me about 3 hours of work.

**Comment by brittAnderson** [comment]
You made a new remote `P363` but you had it pointing your fork - what you should have done was to have `P363` point to MY version `https://github.com/brittAnderson/psych363Practice.git`. 

Then you would have pulled from britt pushed to sridevi and the folder you were missing would have been there. 

Spending hours figuring this stuff out is why this course is all exercises and no 'tests'. It is also what everyone goes through. Courage! Onward!
