### ISSUE TITLE
R Hangman Assessment Resource

### ISSUE THREAD

**Issue by kegsss** [brittAnderson/Intro2Computing4Psychology#34]
Hi everyone,

I've been trying to work my way through the R Hangman conversion from the Python assessment we completed earlier and stumbled across this short guide for some handy tips on converting Python to R code: https://towardsdatascience.com/essential-guide-to-translating-between-python-and-r-7cb18b786e5d?gi=723d3d95e496

Just wanted to share here in the hopes someone else can make use of it as well.

Good luck!

**Comment by brittAnderson** [comment]
Thanks for sharing, but do recall I am asking for less on the R version than the python one. Putting more emphasis on just a couple of useful functions rather than a full scenario. Recommend everyone read the assessment on github and not just assume it is a straight translation.
