### ISSUE TITLE
Python For Loop assessment

### ISSUE THREAD

**Issue by n96khan** [brittAnderson/Intro2Computing4Psychology#35]
How do you keep your sorted list from overwriting your first list? When I go to print both lists, they print out the exact same (both of them alphabetized).

**Comment by scrose5** [comment]
Hi! I'm not sure if this is right but what I did was create 3 different functions (one for printing my list, one for printing the sorted version of my list, and one for printing the "enumerate" function). Then I printed all three functions at the same time. So for example, if I called my list of letters "mylist" I would use: `print(function1(mylist),function2(mylist),function3(mylist)` . Again, I'm not sure if this is what we are supposed to do it but it printed both my unsorted and sorted lists. Hopefully this helps:)

**Comment by brittAnderson** [comment]
If it gets the "right" answer then it is the "right" thing to do. To avoid overwriting another approach would be to create a new variable. `mylist` and `mylistsorted` where the latter would be a copy of the original list after sorting.
