### ISSUE TITLE
running .py file from terminal

### ISSUE THREAD

**Issue by scrose5** [brittAnderson/Intro2Computing4Psychology#36]
Hello,

I tried to run my .py file for the ForLoop assignment through the terminal, since the assignment states that that is how our assignments will be graded, but it won't run. When in emacs, my function and everything works fine but when I try to run it in the terminal it says "invalid syntax". When in the terminal, I directed myself to where my .py file is saved and typed both `python FILENAME.py` and `python3 FILENAME.py` ; the first one doesn't work and the second command gives the "invalid syntax" error. I was wondering if there was a different command that I could try?

**Comment by brittAnderson** [comment]
Best to upload it with a comment and let me see the code to figure out what is going on.
