### ISSUE TITLE
Syntax Print Error

### ISSUE THREAD

**Issue by katevk** [brittAnderson/Intro2Computing4Psychology#39]
Hello, 
I am getting an error when trying to run my python_loop assignment in my terminal. The code works when I htmlize it and it works in a python interpreter. This is the error I get in the terminal. 

./revised_loop_python.py: line 4: syntax error near unexpected token `print'
./revised_loop_python.py: line 4: `    print(i)'

I am not sure where to go from here. Everything I have found online says the syntax is an indent with brackets. Any advice would be greatly appreciated! 
Thanks.

**Comment by bmmunds** [comment]
Hi! Is it possible for you to post your full code?

**Comment by brittAnderson** [comment]
@bmmunds  is right. Show us that section of the code.

**Comment by katevk** [comment]
here it is

![python_loop_error](https://user-images.githubusercontent.com/71223805/98610905-ac18de00-22e8-11eb-9564-f4c8cf617d89.png)

**Comment by brittAnderson** [comment]
When you send a picture we can't try out your code. For such a brief bit of code just cut and paste it into the box. Then I can cut and paste it to test it. 

One issue - but probably not your problem- is that those begin and end source lines are treated as comments in a python file - they are only really meant when embedding your code in an org file. 

Nothing visually jumps out at me, but if you want me to try and debug it then you have to give us the actual code. Not a picture. you could also just drag your file into the box like you did the picture. That would be more helpful.

**Comment by katevk** [comment]
name=["v","a","n","k","e","s","s","e","l"]
for i in name:
	print(i)
x=sorted(name)
print(x)

for i,(first, second) in enumerate(zip(name,sorted(name))):
    print("the first letter of list one is {0}, but it is {1} in the sorted list".format(first, second))

**Comment by brittAnderson** [comment]
Ahhhhh! Indentation. Python cares about white space. You need to indent the stuff that is supposed to be in the for loops:

```
name=["v","a","n","k","e","s","s","e","l"]
for i in name:
    print(i)

x=sorted(name)
print(x)

for i,(first, second) in enumerate(zip(name,sorted(name))):
    print("the first letter of list one is {0}, but it is {1} in the sorted list".format(first, second))
```
