### ISSUE TITLE
"Your First RMD File - Student ID"

### ISSUE THREAD

**Issue by skundurt** [brittAnderson/Intro2Computing4Psychology#4]
For the first RMD file assignment, does the Student ID have to be included in the YAML header? or can it be added as a code chunk?

**Comment by brittAnderson** [comment]
You don't have to have a yaml header - that is optional (yaml = yet another markup language). Put it in the body of the file is fine. Put everything in the body of the file if you want. The yaml header is an Rstudio thing, but you can use native R without it.
