### ISSUE TITLE
Evaluating Code Blocks

### ISSUE THREAD

**Issue by katevk** [brittAnderson/Intro2Computing4Psychology#41]
Hello,

I am unable to execute code blocks when I am in org mode and I am not sure why. When I input C-c C-c the buffer says 'C-c C-c can do nothing useful here'. I have been working around it till now but it slows me down. What am I doing wrong here? 

I have attached an image to illustrate the issue.

![cccc](https://user-images.githubusercontent.com/71223805/99120949-a9253280-25f3-11eb-84a7-cdbaf7809329.png)

Any help would be greatly appreciated! Thanks.

**Comment by brittAnderson** [comment]
I think this is supposed to work out of the box. I was wondering if you have 

    (org-babel-do-load-languages
     'org-babel-load-languages
     '((emacs-lisp . t) 
       (R . t)
       (python . t)
       (latex . t)
       (shell . t)
       ))

in your ~/.emacs.d/init.el file?

**Comment by katevk** [comment]
Thank you
