### ISSUE TITLE
Alternative to using Emacs on Ubuntu/Linux

### ISSUE THREAD

**Issue by brjbrown** [brittAnderson/Intro2Computing4Psychology#42]
Hey everyone, as a Mac user over the past couple weeks I've been having some technical issues with my Ubuntu running, so I just wanted to share that it is possible to use Emacs without booting up Ubuntu. I've had success using [this](https://emacsformacosx.com/) download and following along [with](https://www.youtube.com/watch?v=VP1X7uwBTJE) this video I found Youtube. This way, if you want to use Emacs in the future to take notes or write reports while still staying on MacOS, this will be accessible to you.

Two things I will make mention of: some of the commands are slightly different for this Mac version (importantly, one exports a file using control-C, control-E, and then pressing h twice), and I have yet to be able to integrate R calculations into my documents.

I hope this might help someone!

**Comment by brittAnderson** [comment]
Thanks for sharing Ben.
