### ISSUE TITLE
Downloading file off Github for side-by-side comparison

### ISSUE THREAD

**Issue by OlyaJaworsky** [brittAnderson/Intro2Computing4Psychology#44]
Hello Dr. Anderson, 

I've been searching ways to download github files and loading them in emacs for a side-by-side comparison as shown in the lecture videos, but I have not been able to find a solution that doesn't download the file as html. I'm wondering if there's a way to download the file so that it appears as it should in orgmode?

**Comment by brjbrown** [comment]
In my [Emacs IDE](https://emacsformacosx.com/) I use on my Mac, to produce an Org file I have been just saving the filename as "NAME.org", and then it automatically converts . . . not sure if that might help, I wish you luck 👍

**Comment by brittAnderson** [comment]
The best way would be to "clone" the git repo and open the .org files from where you cloned the directory, but you can also download the "raw" files one at a time. This screenshot shows you where to find the raw button when looking at a file. 
In emacs `C-x 3` opens up two frames side by side. and `ediff-files` will automatically let you scroll between the differences.
![raw](https://user-images.githubusercontent.com/6390408/100631253-82f0d980-32f9-11eb-8c4b-e11d490a2b0d.png)
