### ISSUE TITLE
Plotting in R

### ISSUE THREAD

**Issue by katevk** [brittAnderson/Intro2Computing4Psychology#46]
Hello, I am trying to do the interaction plot in R with ggplot2 but it keeps saying the degreedays cannot be found. Did anyone else have this problem? I have attached an image for reference. 

![degreedays](https://user-images.githubusercontent.com/71223805/101221431-95636e00-367f-11eb-80e1-a8a19c11399b.png)

**Comment by kaitlingaerlan** [comment]
Hi Kate,
I had the same issue and what worked for me was adding the argument “header=TRUE” to the read.csv line
Also, I think you mean to write qplot(df) instead of ggplot(df)

**Comment by brittAnderson** [comment]
If you open up heating.txt in an editor (maybe emacs?) you will see that the first line is the labels for the column header. By adding the line header = true that @kaitlingaerlan mentions lets R take that into account when getting the data. Some other data sets may skip that line and just start with the data. Some files will have even more stuff above the data and you will have to skip multiple lines. read.csv also has an argument for that too.

**Comment by katevk** [comment]
That makes a lot more sense. Thank you for the help!
