### ISSUE TITLE
LEARN Dropbox Due Times

### ISSUE THREAD

**Issue by justnobodyhereyay** [brittAnderson/Intro2Computing4Psychology#47]
Hi, I was wondering if it was intentional for some of the dropboxes on LEARN to be due at inconsistent times like Feb 15, 2021 12:13PM or Feb 20, 2021 12:19PM?

![image](https://user-images.githubusercontent.com/77292844/104238020-f4f32d00-5426-11eb-84db-89d223db5f1a.png)

**Comment by brittAnderson** [comment]
No. Learn defaults to the current time when setting up a dropbox, and I just missed these two. Should be fixed now. Let me know if you see others. But make sure you listen to what I say about due dates and times in the introductory videos on Learn.
