### ISSUE TITLE
Do we need to include a title in the assessment - Your first RMD file.

### ISSUE THREAD

**Issue by w24cai** [brittAnderson/Intro2Computing4Psychology#5]
1. Do we need to include a title in the header in the your first RMD file assessment?  If so, is there any bold or italic requirement for the title?
2. Is there any format requirement for my name and student id? e.g., we need to put name and student id in separate lines.
3. What does inline image mean? 

Thanks in advance!

**Comment by brittAnderson** [comment]
1. Markdown files are not required to have a yaml header. It can be a good practice to have a consistent header in your files, but no you are not required to have a title in the header in general or for this homework.
2. You want it to look "nice". That is the benefit of the markdown syntax. You can easily modify the appearance of a document while you type it. I am using this exercise to get you to practice some of the commands. Have a bit of fun and make it look pleasing, like you might if typing a resume.
3. It means that when I open the html file, or knit your Rmd to Html, the image will just be there, and I won't have to click on a link to visit it.
