### ISSUE TITLE
Mac Xubuntu USB Drive Installation (FULL GUIDE)

### ISSUE THREAD

**Issue by GitrdoneG** [brittAnderson/Intro2Computing4Psychology#50]
Hey everyone, 

I've found a lot of people are experiencing issues with installing Linux on their Mac systems using a bootable USB drive. After several hours of trying different things, I've finally cracked the code. So below is my successful approach to installing Linux on a usb drive. 

Physical things you'll need: Two usb flash drives, both at least around 8-16gb's in size. Ideally 32gb or larger for the usb you're going to run linux on, and 8gb or more for the usb you will be using as a means to install linux on the other desired drive. Also need a mac and usb ports, or a way to connect two usbs to the computer at the same time.

First, download the newest Ubuntu desktop linux software file from ubuntu.com. You should be able to find the download link here: https://ubuntu.com/download/desktop

While that's downloading go into disk utility on your mac (you can search in spotlight to find it) and format both of your USB drives to MS-DOS format - you can do this by clicking erase and then choosing the desired format. 

<img width="822" alt="1" src="https://user-images.githubusercontent.com/72631430/107284802-48f43000-6a2c-11eb-9214-b986d31ece3b.png">

Now it's time to download software that will allow you to flash/mount Linux to your installer usb, so in order to do this, download the software BalenaEtcher. You will find the download link here: https://www.balena.io/etcher/

Once both USBs are formatted to MS-DOS and you have both the latest version of Ubuntu and BalenaEtcher installed, it's time to flash Linux onto your installer driver. So open up BalenaEtcher and first select Flash from File, and select your downloaded version of Ubuntu, then select target as the USB you want to install the Linux installer on (note this is not the usb that you will be running Linux on, this usb only serves as a means in order to properly install linux on the other usb drive). After selecting the target usb you will be able to select Flash and this will create the Linux installer to be used later. You will be notified that the USB is no longer readable, at this point just disregard the message and move on with the installation.

<img width="800" alt="2" src="https://user-images.githubusercontent.com/72631430/107284863-5f01f080-6a2c-11eb-93d3-2558c57554a8.png">

Next, restart your computer, and upon re-boot hold the alt option key in order to pull up your computer's booting options. It's important that you have both usb's connected at this point, one being the linux installer, and the other being a freshly erased MS-DOS formatted drive. From here you will be given the option to boot from either MAC or EFI Boot/something related to this. Select EFI boot. From here the Xubuntu installer will appear, and eventually give you some options to choose from. One being that you can try Xubunutu without install, Install Ubuntu, and a few others. Select Install Ubuntu. (Try Ubuntu will work, although you are very limited in terms of the usable space you have to work with). From this screen some loading and processing screens will appear and you will eventually be brought to the installer page. 

Select your language preferences, and connect to your wifi. I had no issues connecting to my wireless internet, and did not need to install any additional drivers for internet, keyboard, or trackpad use. Next select download updates while installing Ubuntu (you don't have to select this option, I just figured it's easier to get it out of the way now. Then you'll be given prompts for the installation type. DO NOT SELECT ERASE DISK AND INSTALL. Instead, select Something else and continue. 

From here you'll be able to see all your computers storage and connected drives. Avoid selecting anything with sda as this is what the mac operating system is on. Instead select, sdc, you will also likely see fat32 beside it, which is what you just formatted the drive to be. So make sure you click on your usb - another way to confirm it is the usb you want to install linux onto is by checking the size, it will show a size in mbs, so divide this number by 1000 and you should get the rough size of what your usb says in gb. Ie. size of 30750mb indicates a 32gb usb. Now there is likely a partition under this usb drive, so select the partition underneath the main sdc drive and click the minus button. This will create Free Space on the drive that you will be able to install Ubuntu onto. 

<img width="1112" alt="3" src="https://user-images.githubusercontent.com/72631430/107284964-7e991900-6a2c-11eb-99f0-7ddbf4930f73.png">

After hitting the minus option on the USB's labelled partition(s), the sdc drive device will be renamed Free Space with no other options underneath it. If there are other partitions/options listed underneath it - meaning they belong to this specific drive and not a different drive, select them and hit the minus button again until the device has no partitions and is completely free space. Now select the sdc Free Space device and click the plus button. 

<img width="1140" alt="4" src="https://user-images.githubusercontent.com/72631430/107285306-f109f900-6a2c-11eb-961e-58083a0aef25.png">

From here it will bring up a screen to partition the drive. This is what you want in order to format the drive properly for the linux installation. So, there are a few options that need to be selected correctly in order to do this. First make sure that the size is maxed out, ie. the plus button can no longer be pressed meaning that the entire drive will be partitioned for linux. Then, select Primary Type and Beginning of this space for new partition location. Use it as a EXT4 Journaling File System with the "/" symbol as the mount point and select ok. 

<img width="721" alt="5" src="https://user-images.githubusercontent.com/72631430/107285590-65449c80-6a2d-11eb-9c0e-df7926f58fd1.png">

Now you've created a properly formatted drive to install Linux onto. So below on the dropdown menu select your newly formatted usb device as the source for boot loader installation. By doing so it will automatically put a checkmark on your usb device in the upper screen in order to confirm this is the drive you'd like to install linux onto.

<img width="1261" alt="6" src="https://user-images.githubusercontent.com/72631430/107285982-f7e53b80-6a2d-11eb-9d00-93e606d28fbd.png">

Now hit Install Now to begin installing linux on your flash drive. At this point there will be a couple prompts asking you to continue, or press okay. Do not hit cancel, hit continue/ok in order to continue the install process. 

This part may take a while, but once it's done you will be able to select your time region, keyboard layout and enter your account information. After this the operating system will boot up and you will have successfully installed Ubuntu onto your usb device using a mac! 

Also keep in mind you'll likely have to restart the computer to install some software updates, so in order to do that, click the menu icon on the top left of your screen and select the power button. During restart hold the option key again to boot into your linux drive through the EFI boot option and then your updates will be installed and your operating system is ready to use once again. 

So now whenever you need to use linux just plug in your dedicated usb, restart your computer, hold the option key upon boot, select EFI boot, and you're in! The other installer usb can be erased and formatted for other use. 

Thanks for reading and let me know if you guys have any issues with this process!

**Comment by brittAnderson** [comment]
thanks @GitrdoneG . 

Some similar ideas are also described in these videos for people who like to listen more than read. 

https://vimeo.com/499572407 

https://vimeo.com/499617484

**Comment by brittAnderson** [comment]
Closing so it doesn't keep popping up on my todo list, but a great write up.
