### ISSUE TITLE
Hangman in Python

### ISSUE THREAD

**Issue by asmaKarovalia** [brittAnderson/Intro2Computing4Psychology#55]
Hello, 

I have my code done, however, it does not print out the "you win" or "you lose" if the user exceeds the maximum amount. I've shown my code below and have tried to figure out where I am going wrong, but I wanted to post it here in case anyone had some insight. Thanks!

`def findIndices(word, letter):
    indices = []
    for i in range(len(word)):
        if word[i] == letter:
            indices.append(i)
    return indices
print("Let's play Hangman!")
def hangman():
    maximum = 8
    current = 0
    wor_lis = list("smile")
    cor_guess_list = []
    guess_list = []
    letter = input("Enter a letter: ")
    if list.sort(cor_guess_list) == wor_lis:
        print("You win")
    elif maximum >= current:
        print(findIndices("smile", letter))
        if letter in wor_lis:
            cor_guess_list.append(letter)
            current += 1
            hangman()
        else:
            guess_list.append(letter)
            current += 1
            hangman()
    else:
        print("You lose")
        
hangman()`

**Comment by asmaKarovalia** [comment]
Hello, I think I figured out what the problem was. In the if statement, the two hangman() seemed to be the problem.

if letter in wor_lis:
            cor_guess_list.append(letter)
            current += 1
            hangman()
        else:
            guess_list.append(letter)
            current += 1
            hangman()

I think what happens here is that the game restarts, so it is not able to register the # of tries the user has. I removed the hangman() from these two areas, and it seemed to work and showed the "you lose" statement. 

Wanted to share in case anyone had the same issue.

**Comment by brittAnderson** [comment]
Whitespace matters in python. Without seeing the indents it is hard to know exactly how the code is being interpreted, but you might be writing a recursive function: a function that calls itself. That is legal, but can be tricky and probably not what you want to be doing.  If it works, great. But another approach would be just to use one of the types of loops you practiced, for or while. Something like `for i in range (current, maximum) ... `or `while current < maximum ... `and make sure you do the trick of updating current each time through the loop.
