### ISSUE TITLE
Question About Hangman in R Assignment

### ISSUE THREAD

**Issue by aamcewin** [brittAnderson/Intro2Computing4Psychology#56]
Hello, and I hope all is well with you,

When I created Hangman in Python, I printed the Word I'd selected and which letters the player revealed with their guess if they guessed correctly, rather than printing the list of indices where the letter exists. I can and will still try to figure out how to do this for R, but for a functional game, would it make more sense to print the word and letters revealed? Or should I stick to trying to print the indices of where letters exist? I can see about doing both, as I would still like players to be able to see the letters they've revealed in the word.

**Comment by brittAnderson** [comment]
For a functional game you would want to do a lot differently. But here we are just using hangman to give us something to practice on and as a basis for comparing python and R. Text processing is easier in python and I did not want people spending a ton of time tweaking a game interface. I wanted them to spend some time getting familiar with the languages and coding. If you have time and interest to make it nicer, great, do so, but it is not required. Mostly, just get the basic mechanics coded and move on to the next thing. The importance of the next lessons is greater than getting hangman right.
