### ISSUE TITLE
Version Control and Pull Request - Authentication Change

### ISSUE THREAD

**Issue by ashamann** [brittAnderson/Intro2Computing4Psychology#57]
Hello all, In the assignment "Version Control and Pull Request", a person's GitHub username and password were used to authenticate their GitHub account to complete the push/pull request. In the near future, this form of authentication will be deprecated. Instead, token activation will be required. More information can be found on https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ . Detailed steps on how to create a token can be found at https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token. Have a good one!

**Comment by brittAnderson** [comment]
Thanks. Good to know. I have started to do this and it was not that hard to set up. The hardest part was finding the information. Nice to have it here.
