### ISSUE TITLE
Error in Emacs While Working on Plotting

### ISSUE THREAD

**Issue by aamcewin** [brittAnderson/Intro2Computing4Psychology#59]
I've encountered an issue when I attempt to execute Python code blocks within emacs using C-c C-c:

Warning (python): Your ‘python-shell-interpreter’ doesn’t seem to support readline, yet ‘python-shell-completion-native-enable’ was t and "python3" is not part of the ‘python-shell-completion-native-disabled-interpreters’ list.  Native completions have been disabled locally. 

I don't entirely understand what this warning message means, but I suspect it is the source of my recent troubles attempting this assignment. It's strange because I *am* able to execute M-x 'run-python', but I'm not sure whether something is wrong with my org-babel lines in my init.el file that's preventing me from executing python code blocks in emacs. When I checked M-x find-function python-shell-completion-native-try to see if I was experiencing [this](https://emacs.stackexchange.com/questions/30082/your-python-shell-interpreter-doesn-t-seem-to-support-readline) problem, it appears as though I did not need to make this suggested fix, as the end of the line does indeed say nil "_"))) rather than nil " "))) in that location. So I'm at a bit of a loss and would appreciate any available guidance!

I hope that the problem is not with my init file, as I'd shared that with somebody else recently and will have to warn them if my file has errors in it. The relevant lines in it look like this:
```

(setq org-confirm-babel-evaluate nil)
(setq org-babel-python-command "python3")

(org-babel-do-load-languages
 'org-babel-load-languages
 '((emacs-lisp . t)
   (R . t)
   (python . t)))
```

**Comment by brittAnderson** [comment]
If you do not get any error messages when you start emacs than your init file has correct syntax. 
You can ignore this warning for the most part. It is telling you that emacs doen't know how to guess what you are typing and complete it for you. 

If you don't like the warning I think you can turn it off with this in your init file

    (setq python-shell-completion-native-enable nil)
    
If you want to try and fix the problem you can probably do so (after updating and upgrading with "apt") by pip installing gnureadline. But I don't think I would bother tweaking your emacs now, but rather moving on to new material.
