### ISSUE TITLE
Init.File Error in Report Generation

### ISSUE THREAD

**Issue by isimione** [brittAnderson/Intro2Computing4Psychology#63]
When trying to access the 'reportGen' via the directory in emacs (e.g., C-x, C-d; type gitRepos/Intro2Computing4Psychology/codeExamples/reportGen' I always end up making another 'new' file as opposed to accessing the one repository online (cannot see testLatex.org file).
I also get the error message, Symbol's function definition is void: pdf-tools-install; this is after I added the code (pdf-tools-install to my init.el file)
Below I've attached how my init.el file looks currently. 
Symbol's function definition is void: pdf-tools-install

`(require``` 'package)
(add-to-list 'package-archives '("melpa" ."http://melpa.org/packages/") t)
(package-initialize)

(use-package elpy
:ensure t
:init (elpy-enable))
 
(use-package ess
:ensure t
)
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages (quote (ess-R-data-view ess htmlize use-package))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

(setq org-confirm-babel-evaluate nil)
(setq org-babel-python-command "python3")

  (org-babel-do-load-languages
  'org-babel-load-languages
  '((emacs-lisp . t) 
  (R . t)
  (python . t)))

(setq elpy-rpc-python-command "python3")

(use-package elpy
  :ensure t
  :init
  (elpy-enable))

(setq python-shell-completion-native-disables-interpreters '("python3"))

(pdf-tools-install)``

**Comment by brittAnderson** [comment]
1. Did you clone the repository? 
2. Did you create the gitRepos directory?
3. You are using a relative path. Are you sure there is actually a directory there?
4. You don't want to install the pdf-tools package multiple times. There are many ways to install it. Given your tight timeline I suggest you remove that line from your init.el file. Make sure that when you close and restart emacs there are no errors. M-x package-list-packages. Scroll down or search for pdf-tools. Put an "i" next to it for install. Type "x" for execute the installation. Let it do its thing. See if you get a happy face from the installation :0

**Comment by isimione** [comment]
I did clone and create a gitRepos directory previously (I had to for other the pull request), but you're right, the directory wasn't there. I recreated and cloned the directory and now am able to access the file! Thank you!
