### ISSUE TITLE
Downloading Linux for Mac with Intel chip 

### ISSUE THREAD

**Issue by h5mittal** [brittAnderson/Intro2Computing4Psychology#66]
I have a Mac with intel chip ,however I am not able  to download Linux as virtual machine for my Mac . Any steps to download it will be really helpful. I have attached the following screen shot of error .I tried looking for videos online for downloading it ,however I am unable to download and understand the process.

<img width="1440" alt="Screen Shot 2022-05-08 at 3 01 34 AM" src="https://user-images.githubusercontent.com/105144619/167285696-328da4d5-0cbf-405c-aad9-4b588180b646.png">

**Comment by brittAnderson** [comment]
Did you watch the video that I made of this process?

**Comment by h5mittal** [comment]
Yes I was able to watch the video . I am able to access the virtual machine now because I figured that that it was already installed in my computer .Therefore  if any other student is facing this problem they may already have virtual machine in there Intel Mac.However I am unable to download the Xubuntu to my Virtual box .
