### ISSUE TITLE
Your First Rmd File— Caption not appearing in knit file

### ISSUE THREAD

**Issue by flwcaron** [brittAnderson/Intro2Computing4Psychology#67]
Hey y'all! Working on the first Rmd file assignment at the moment, and I seem to somehow have run into an issue on what I would usually expect to be the least problematic part of the requirements: the caption on my inline image? I've got everything else working including the image, but for some reason can't seem to get the caption to appear. I've already tried removing periods from it, naming it using only one word, and I'm using a Google Photos image of my own if any of that's relevant, but I don't see how it could be. Anyone else getting the same thing? Thanks!

François

**Comment by anhl07** [comment]
using ![insert caption/image description](link to image) worked for me in terms of displaying both the caption and inline image

**Comment by brittAnderson** [comment]
Thanks for using the issues. Try  pasting your code into your issue. Then we can cut and paste and try to find the typo. You have a way to add code (look for the little <> above).

This works for me. 

    ---
    title: Test Document
    ---
    # This is a test of a figure with caption.
    
    ![This is a picture of a
    Brain](https://brittlab.uwaterloo.ca/assets/siteassets/logo3.png)

    And thus it was.

**Comment by flwcaron** [comment]
For sure, here's the code!

`**François Caron**
\
*20707022*
\
\
The Psychology department's web page, because it seemed relevant: <https://uwaterloo.ca/psychology/>
\
\
![Remy.exe has crashed.][id]

[id]: https://lh3.googleusercontent.com/2HddDn-HANBM_W04bX2DKukj26GhqGDOoH2ehSl-zBCn3hDo4-E4HP5TbupmUUK1UmHQ4n5h4knh0-G4PDsAWzzswu3CE_HbiBK2qp5kzMYNVpp-ch92UIsJhzfxU19yrNmFpJZ5YR2bjqveugl2ydNW4EdAsoqIZEPN0bMZaxWmnJqumYFgQJYAdU8FR1GI7p-oK7wUGjB84PZGuuRjIxx5PVqijeUvtgQYFQTWrP5wtTb1AlZAVfzCe_27ZJQMXRCfNyvrpqzWrcDzbq-Ca1sLDy6pX2KhTAZ3SlGmZFUj-o0aFwn7YzlDJBS2DJoK837Uzi1pT05SdxVz8mLDqoJQI7f2qkOWJT8LvFJEkQ5WJqtMQIrjE6-ykXdhg1YXwbR_6VQ3pe5suwWeLIs-NiSxp65koKC5wwTX1vVOmlmRcNHlEmOkHIkPUqozM8rQJ7zw9Lw0y17KBTOizBybQQWumyasgyWi12Hoc-qit-8uIM4ZzQViy_N8gQcQbBb0z-S_XTQKz9-EOjeUW6mPUYr3vPWPFCeDcB18-lvjSRiDFJM3Cj-N69MPL32VSx3E7mPfDQLKv5FfT_Z3tuPcjCHrpXoY6JdSlvTd80IohMDgMOaOUBeYwMOSu1Pp7B53nunX8MDK-y7T5FrYr8HTetvh7o2yuT5GPmgRxwInOHVTIxVvsprKR28rV_IuxdW5srZmMkC2wlV_VVr7oKa4twvAsDW0-pZZ-aXd3c17ZLqqigeQmMb3aPwWGObW5RDzN4U6M61x6cNch908f87mtWCsNPtL_fr24aBqPqPuDC2GsBL3sB_vo2zyaFwSHlEq2yFmGZwknqfvOWFOoRwcYBQ41roPEh0O7DoufT83w-I=w523-h929-no?authuser=0`

**Comment by flwcaron** [comment]
For whatever reason now the caption appears in the comment but not the image, which might be due to the image being one of my own Google Photos? I'll try with a regular picture found off the internet and see if that (for whatever) fixes both issues.

**Comment by flwcaron** [comment]
Tried with a random image off the web, same issue when knitting:

`**François Caron**
\
*20707022*
\
\
The Psychology department's web page, because it seemed relevant: <https://uwaterloo.ca/psychology/>
\
\
![Here, have a different mini schnauzer instead][id]

[id]: https://www.thesprucepets.com/thmb/ZI1fO1jsXEsdv7VSmDYoVllQS2g=/1775x1183/filters:fill(auto,1)/GettyImages-998982774-8315e94484c84de090cfa12dbbe0d400.jpg`

**Comment by flwcaron** [comment]
Here's the raw code itself, in case the insert code thing I was doing doesn't work for y'all:

**François Caron**
\
*20707022*
\
\
The Psychology department's web page, because it seemed relevant: <https://uwaterloo.ca/psychology/>
\
\
![Here, have a different mini schnauzer instead][id]

[id]: https://www.thesprucepets.com/thmb/ZI1fO1jsXEsdv7VSmDYoVllQS2g=/1775x1183/filters:fill(auto,1)/GettyImages-998982774-8315e94484c84de090cfa12dbbe0d400.jpg

**Comment by brittAnderson** [comment]
You are not quoting your code. Look at my response above and now look at yours. See how mine is all gray and the code appears as code? Use the code formatting option as requested to include the code.

`This is formatted as code`

This is not.

    You can indent each line by four spaces
    And that looks like code too.

**Comment by flwcaron** [comment]
Sorry about that, I was using the quote feature the first two times but the button on the comment doesn't actually work— I had to use triple backticks, apparently. My bad!

```
**François Caron**
\
*20707022*
\
\
The Psychology department's web page, because it seemed relevant: <https://uwaterloo.ca/psychology/>
\
\
![Here, have a different mini schnauzer instead][id]

[id]: https://www.thesprucepets.com/thmb/ZI1fO1jsXEsdv7VSmDYoVllQS2g=/1775x1183/filters:fill(auto,1)/GettyImages-998982774-8315e94484c84de090cfa12dbbe0d400.jpg ```

**Comment by anhl07** [comment]
Hey you should be able to just have your code without needing the backslashes, because that's reserved for a different function in Markdown

`*student ID*` would italicize it when knit to HTML like this` _student id_ `,`_ and `\*student ID\*` would allow you to generate the actual characters instead of being Markdown syntax so it'd look like this ` *student id*` 

I'd suggest doing this

```
**François Caron**

*20707022*

The Psychology department's web page, because it seemed relevant: <https://uwaterloo.ca/psychology/>

![Here, have a different mini schnauzer instead](https://www.thesprucepets.com/thmb/ZI1fO1jsXEsdv7VSmDYoVllQS2g=/1775x1183/filters:fill(auto,1)/GettyImages-998982774-8315e94484c84de090cfa12dbbe0d400.jpg)
```
 or if you want to keep your original code, then just remove the backslashes
```
**François Caron**

*20707022*

The Psychology department's web page, because it seemed relevant: <https://uwaterloo.ca/psychology/>


![Here, have a different mini schnauzer instead][id]

[id]:https://www.thesprucepets.com/thmb/ZI1fO1jsXEsdv7VSmDYoVllQS2g=/1775x1183/filters:fill(auto,1)/GettyImages-998982774-8315e94484c84de090cfa12dbbe0d400.jpg

```
which would give you this HTML output
![image](https://user-images.githubusercontent.com/104758694/168936257-bb71839a-aac4-43c9-b40d-9beb8ad36469.png)
