### ISSUE TITLE
Printing the names of other datasets available in RStudio

### ISSUE THREAD

**Issue by lchalupk** [brittAnderson/Intro2Computing4Psychology#69]
Hello,

I've found a command that lists all the available datasets in RStudio, but when I try to print the data output by this command RStudio generates a separate file and outputs the text into the file instead of the console. Additionally, when I knit the file the function I am using does not output anything into the HTML file. 

I was wondering if this is okay for the assignment, or if we should have a function that produces this list of datasets also output to the HTML file. 

Any input is appreciated! Thanks.

**Comment by anhl07** [comment]
would you be able to post a sc of what you're seeing? 
If you use the `library(help="datasets")` then it'll open up the doc for the 'datasets' package. 
For me, after I had chosen a dataset (e.g., trees), and used `names(trees)` it did print the column names in the console 
`> names(trees)
[1] "Girth"  "Height" "Volume"` 

But if you're talking making R Markdown evaluate R codes, you'll have to use R chunks which begins like ` ```{r}  ` and ends with 3 backticks ` ``` ` , it evaluates everything in that chunk, like if I did

` ``` {r} 
names(trees)
summary(trees)
 ``` ` 

the output in the console would look like

`> names(trees)
[1] "Girth"  "Height" "Volume"
> summary(trees)
     Girth           Height       Volume     
 Min.   : 8.30   Min.   :63   Min.   :10.20  
 1st Qu.:11.05   1st Qu.:72   1st Qu.:19.40  
 Median :12.90   Median :76   Median :24.20  
 Mean   :13.25   Mean   :76   Mean   :30.17  
 3rd Qu.:15.25   3rd Qu.:80   3rd Qu.:37.30  
 Max.   :20.60   Max.   :87   Max.   :77.00 `

and when knit to HTML it'll look like this

![Capture](https://user-images.githubusercontent.com/104758694/168924453-7ab3d09f-92f7-430b-85eb-02d4b596dddc.JPG)

**Comment by lchalupk** [comment]
The code providing the error is:
```{r}
`data()`
```{r}
When run in RStudio, it returns a new text file containing all of the available packages, however after knitting the file, it simply comes up for me as echo'd code in the HTML file with no output below. the same thing happens when I use data() as a parameter for print().

Is there a method to get data() to output to HTML in order to print all the names of the built-in datasets within R?
