### ISSUE TITLE
Testing persistence on the USB 

### ISSUE THREAD

**Issue by s296ahme** [brittAnderson/Intro2Computing4Psychology#7]
I'd like to run Xubuntu on my USB and work on that. I was able to use boot Xubuntu with the USB, but when I test for persistence by saving the text file on my desktop, it doesn't appear after I shut down the system and open it again.

I tried again, this time saving the text file to my USB and I found that it was still there, however, doing it that way doesn't save my wifi network because it seems like its rebooting as if its the first time or "new" each time. 

How can I make my USB persistent such that the changes I make while running Xubuntu will be saved? The USB I'm using is new, its a Netac 32 GB. Please let me know. 

Thanks!

**Comment by n96khan** [comment]
Would it be okay to download and work out of Oracle VirtualBox? I was told that I wouldn't have to interrupt the booting system each time I wanted to run XUbuntu.

**Comment by brittAnderson** [comment]
> I'd like to run Xubuntu on my USB and work on that. I was able to use boot Xubuntu with the USB, but when I test for persistence by saving the text file on my desktop, it doesn't appear after I shut down the system and open it again.
> 
> I tried again, this time saving the text file to my USB and I found that it was still there, however, doing it that way doesn't save my wifi network because it seems like its rebooting as if its the first time or "new" each time.
> 
> How can I make my USB persistent such that the changes I make while running Xubuntu will be saved? The USB I'm using is new, its a Netac 32 GB. Please let me know.
> 
> Thanks!

Need to know how you created the USB. Did you use Rufus? Did you click the little box for persistence and increase the size of the persistent partition like it shows in the video? If you give more details, I can try to help figure out what is missing.

**Comment by brittAnderson** [comment]
> Would it be okay to download and work out of Oracle VirtualBox? I was told that I wouldn't have to interrupt the booting system each time I wanted to run XUbuntu.

If you have the ability to set up a VM that is fine by me. A lot of students won't know what a VM is, and we don't have time to teach it here, but it is okay - in fact I think I mention that as one of the acceptable alternatives some where in the course material.

**Comment by s296ahme** [comment]
@brittAnderson Yes I used Rufus and increased the persistence partition to the max which was 28GB for me. I noticed that once everything loaded on Rufus and the button changed to “Ready”, if I went to “This PC” on my laptop, I can see Xubuntu as a little section of the USB, but also a USB storage of 28GB, which I assume is the persistence partition storage space. 

I’m wondering if it’s because I’m re-using the USB? I had originally used Rufus to download Ubuntu onto the USB but I didn’t change the persistence partition. I then re-did everything following your videos. 

I also noticed that when I downloaded Rufus 3.11 (the first option that was bolded like you did) when I opened it, on the top where it says the program name, mine said “Portable” in brackets where as yours didn’t. Not sure if that matters. 

Let me know, thank you!

**Comment by brittAnderson** [comment]
I think you probably have two versions of the iso on your USB: the one you downloaded and the one you created with Rufus. Although it may involve a few more steps the thing to do is probably drag the iso you downloaded off the internet to you laptop and then format your USB. Formatting means you will wipe out everything on it and create a clean USB. There are several methods you can use (I found this listing here: https://www.windowscentral.com/how-format-usb-flash-drive-windows-10) . Now with the xubuntu iso file on your laptop, and the USB "pristine", resume the Rufus process selecting the iso from your laptop, and the USB that is plugged in and as you go make sure that none of the buttons about persistence get "reset" before you click the "do it" button. If that has the same problem we can schedule a webex session for me to watch your screen as you go through the steps.

**Comment by s296ahme** [comment]
Hi @brittAnderson, I followed the steps to format the USB, and it seemed to clear everything, however when I click "This PC" it still shows the little USB icon and the Xubuntu folder even though it's empty. I went on Rufus to try to re-do the steps of getting the Xubuntu file on my laptop to the USB, but I got a message that says "the volume does not contain a recognized file system" (which I have attached). Afterwards, I got an error message that said something along the lines of the device is in use/not working so the progress bar on Rufus changed to "failed". 

<img width="657" alt="saraAhmed_notAccessibleMessage" src="https://user-images.githubusercontent.com/70985284/93909201-851d3300-fccd-11ea-99e2-a5bd789a5d6d.png">

**Comment by brittAnderson** [comment]
Show us the rufus screen that is obscured in the back ground

**Comment by s296ahme** [comment]
<img width="692" alt="saraAhmed_Access2deviceDenied" src="https://user-images.githubusercontent.com/70985284/93911390-52286e80-fcd0-11ea-9c94-c6e7713ad6ca.png">

**Comment by brittAnderson** [comment]
Somewhere in the process you created multiple partitions on your usb. See how you have both a D and E letter and it tells you have multiple partitions? The simplest thing is to just have the whole disk one partition. You say you followed instructions, but you don't say which steps exactly. There is a little drop down arrow next to your D/E multiple partitions. You can try selecting one of those and seeing if that works, but better yet would be to just have a single "FAT32" file system on a single partition. You can make such many different ways - they were in the link from last time; make sure and share which technique you are using, and the exact steps you follow. Don't ignore any error messages along the way. They may be the clue we need. 

If you have another USB around you can try that instead.

**Comment by s296ahme** [comment]
The dropdown on the top beside "Multiple Partitions (D:) (E:)" doesn't have any options to select from. 

I'm going to try it on a different USB to see if works there.

**Comment by brittAnderson** [comment]
Okay. Let's close this issue and just email me directly if problem persists. If you are still having problems I will put out a "call" to any other students that want to schedule a joint online meeting to try and to things together.
