### ISSUE TITLE
First Rmd File Tip: How to Get Online Picture Link

### ISSUE THREAD

**Issue by shirleyrima** [brittAnderson/Intro2Computing4Psychology#70]
Hi everyone! Hope you all find the semester going well. If anyone is having trouble getting the link of online picture, this works for me on Mac:

1. Open the website that has the picture you want
2. Right click on the picture
3. Select _Copy Image Address_ option
4. Then you will have the link of the picture in your clipboard, and you can copy that in your Rmd file.

This can be trivial to most of you, but I had been struggling with it for an hour. Hence I feel it would be nice to address it here in case if anyone is looking for it. 

Shirley

**Comment by brittAnderson** [comment]
Thanks for posting. If it took you awhile, it is probably taking some others a while too. Posts like this mean they spend less time.

**Comment by Arichterpowell** [comment]
Thank you so much for posting this! It really helped me
