### ISSUE TITLE
Tip for Installing Ubuntu on Mac with Intel Chip: Solving "Kernel driver not installed" Error

### ISSUE THREAD

**Issue by shirleyrima** [brittAnderson/Intro2Computing4Psychology#71]
Hi, 

I was installing Ubuntu in a Mac with Intel chip, and I found the videos https://vimeo.com/699876529 Caa-Cae very helpful. All I did was just following the videos step by step, and it was quite straight forward. Thanks again for making them!

However, I did encounter an error message bellow when I tried to start Ubuntu (~1:00 in Cad video), which was "Kernel driver not installed (rc=-1908)".
![Screen Shot 2022-05-23 at 3 42 03 AM](https://user-images.githubusercontent.com/59749978/169777957-bd11c54e-a089-4bec-a5f9-d25cdd852d6f.png)
To fix this issue, I found this link https://medium.com/@Aenon/mac-virtualbox-kernel-driver-error-df39e7e10cd8 very useful. Basically all I had to do was to manually change some setting preferences in the Privacy & Security.

Hope it helps some of you.

Shirley

**Comment by WisamAlkheder** [comment]
Yes I encountered this issue yesterday, Thanks for sharing this here.

**Comment by brittAnderson** [comment]
There are also some links and discussions in the learn forum. Great to have the answers posted in both places. Thanks.
