### ISSUE TITLE
Printing only even numbers in a loop

### ISSUE THREAD

**Issue by WisamAlkheder** [brittAnderson/Intro2Computing4Psychology#72]
Hi everyone,

I'm having trouble figuring out how to only print the even numbers in a for loop seq.

I was able to do this:

`> for(i in seq(1:10)){
+ print(i%%2)}
[1] 1
[1] 0
[1] 1
[1] 0
[1] 1
[1] 0
[1] 1
[1] 0
[1] 1
[1] 0`

And I can produce an answer whether the number is even or odd (true or false).

How do I limit the printing to the even numbers though? without having to show the rest of the numbers (or zeros).

Best,
Wisam

**Comment by mps5199** [comment]
You can use an if statement to check if the number is even, and write a print command in the body of that if function.That would print only the even numbers.
Also , when you write "  i %%2  " you just calculate the mod value(remainder) when "i" is divided by 2, you also need to check if thats equal to 0 to make sure "i" is even

**Comment by brittAnderson** [comment]
Thanks Mohanpreet. 
If this is still not clear come to class tomorrow and we can go through it.

**Comment by WisamAlkheder** [comment]
Thank you, Mohan and Dr. Anderso.
See you in class.
