### ISSUE TITLE
Install Ubuntu (on Windows 11) - Issue with finding Hypervisor Manager

### ISSUE THREAD

**Issue by flwcaron** [brittAnderson/Intro2Computing4Psychology#73]
Hi there! I'm currently in the process of setting up the virtual machine on my Windows 11 laptop, and got into the BIOS and activated the feature under the "Turn Windows features on or off" screen fine, but the manager option isn't showing up when I search it in the Windows search bar, and upon further research online, I'm seeing that Windows 11 Home doesn't natively have any hypervisor managers, only the other versions. Am I missing something, or doing something wrong maybe? Thanks in advance!

François

**Comment by brittAnderson** [comment]
Do you follow the discussion forum in learn?
https://learn.uwaterloo.ca/d2l/le/802943/discussions/threads/2527643/View

**Comment by flwcaron** [comment]
I did not (though I am now), thanks Britt! I think I've got it working now— I guess the native hypervisor option wasn't the same as the actual Hyper-V feature, so I've got the manager now that I installed that one.
