### ISSUE TITLE
Pull Request Assessment Permission Issues

### ISSUE THREAD

**Issue by flwcaron** [brittAnderson/Intro2Computing4Psychology#78]
Hey y'all! Currently working on catching up on a few of the more recent assessments, and I'm running into an issue while working on the pull request stuff where most of the git commands I try to use in the terminal (like adding remotes, fetching britt, etc.) keep giving me a Permission Denied error, forcing me to use sudo, and now that I'm trying to create a new file in the gitnames directory, it's giving me yet another "error writing flwcaron.txt: permission denied" error. Feel like this might not be normal, so I thought I'd share here to see if anyone else ran into the same issue or might have a solution. Thanks a lot in advance!

François

**Comment by brittAnderson** [comment]
Did you create a personal access token?
