### ISSUE TITLE
Hangman in R

### ISSUE THREAD

**Issue by TheCanasian23** [brittAnderson/Intro2Computing4Psychology#81]
I usually write in python so I might be missing some brackets or my logic might not work for r. I honestly don't know why it doesn't work
![image](https://user-images.githubusercontent.com/104944781/176616851-a1596bc2-b6de-44f8-bef0-58cfab58f86f.png)

**Comment by brittAnderson** [comment]
We can't edit a screen shot. Use the code  block option (look for the <> icon) and insert your code into the issue. Then also give a concrete problem of what doesn't work means and we can try to help you. 

Also, you do not want to use as variable names words that have special meaning in a language. `time` is a built in function in R. Try a different name

**Comment by TheCanasian23** [comment]
`hangman=function(word, guess){
  x=nchar(word)
  sprintf("The word is %d letters long",x)
  sprintf("You have %d number of incorrect guesses.", guess)
  copy=word
  counter = 0
  while (guess!=0){
    letter=readline(prompt="Please enter the letter you would like to check:")
    position=list()
    let=FALSE
    for (a in range(nchar(copy))){
      if (substr(copy,a,a)==letter){
        append(position,a+1)
        sub(substr(copy,a,a),"",copy)
        let=TRUE
        counter=counter+1
      }
    }
    print(position)
    if (counter==(nchar(word))){
      return(print("You win! The word was:", word))
    }
    if (let==FALSE){
      guess=guess-1
    }
  }
  return(print("You lose! The word was:",word))
}

times=function(maxx){
  maxx = readline(prompt="Please enter the maximum number of incorrect guesses as a positive integer:")
  maxx = as.integer(maxx);
  hangman("hello",maxx)
}
`
So the file will take the maximum number of incorrect guesses and letter you want to guess, but it's not correctly check if the letter is right or not. It also not printing how long the word is, how many incorrect guesses you have to start, and an error occurs from the return print statement saying "invalid printing digits -2137483648"

**Comment by brittAnderson** [comment]
Your problems are traceable to a few things.

- You are working on too complex a piece of code. Build it inside out. Test trivial pieces of code. Make them work and then grown the application from functioning bits. You have so many errors here it is hard to debug, and that is because you wrote a big piece of code before you started testing. 
- R is not python. Don't assume the two languages are the same or do the same. Look at range. It does not do in R what it does in Python, but you assumed it did. 
- As you got frustrated you got sloppy. Even though you correctly used `sprintf` at the top of your code you then failed to use it correctly later when you kept typing `print` when you meant `sprintf`, and you did not include the proper formatting characters. 
 
```
    hangman=function(targetWord = "hello", guess){
        x=nchar(targetWord)
        sprintf("The word is %d letters long",x)
        sprintf("You have %d number of incorrect guesses.", guess)
        copyTargetWord = targetWord
        displayCorrectGuesses = rep("_",x)
        print(displayCorrectGuesses)
        position = list()
        counter = 0
        while (guess!=0){
            letter=readline(prompt="Please enter the letter you would like to check:")
            let=FALSE
            for (a in seq(nchar(copyTargetWord))){
                if (substr(copyTargetWord,a,a)==letter){
                    displayCorrectGuesses[a] <- letter
                    sub(substr(copyTargetWord,a,a),"",copyTargetWord)
                    print(copyTargetWord)
                    let=TRUE
                    counter=counter+1
                }
            }
            print(displayCorrectGuesses)
            if (counter==(nchar(targetWord))){
                return(sprintf("You win! The word was: %s", targetWord))
            }
            if (let==FALSE){
                guess=guess-1
            }
        }
        return(sprintf("You lose! The word was: %s",targetWord))
    }
```

Try `hangman("psychology", 5)`
