### ISSUE TITLE
Unable to Install Psychopy

### ISSUE THREAD

**Issue by nkugatha** [brittAnderson/Intro2Computing4Psychology#84]
Hello! 

I'm trying to install Psychopy but I keep getting the following error message:

 **error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]**
  
  **note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure**

**× Encountered error while trying to install package.
╰─> pyo**

**note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.**

 
This is the pip3 version I currently have:
pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

Was wondering if anyone could help me get Psychopy up and running?

**Comment by SixuanChen** [comment]
I was able to solve this problem by doing the following in my Ubuntu virtual machine:

Install a psychopy with no dependency using command:
pip install psychopy --no-deps
Run a py file and see what are the required dependencies. 
Install them manually through pip one by one. (If you do not have pip then you should do : sudo apt install python3-pip)

For me, I installed bidi and arabic-reshaper packages through :
pip install python-bidi
pip install arabi-reshaper
I hope this could help you!

Sixuan
