### ISSUE TITLE
Xubuntu bootable USB on mac - no internet connection

### ISSUE THREAD

**Issue by seanrowe95** [brittAnderson/Intro2Computing4Psychology#9]
I used a friend's computer to use Rufus to make a bootable USB to use on my Mac. Its able to boot up, I can see the desktop, and I have persistence. However, I can't seem to connect to the internet (and hence can't update or install stuff).

![IMG_20200926_131409](https://user-images.githubusercontent.com/33583345/94346390-620ac000-fffa-11ea-9e51-2f6c77f686b7.jpg)

I also tried to connect with an Ethernet cable, to no avail. Has anyone else had issues connecting to the internet from their bootable usb?

**Comment by seanrowe95** [comment]
**Update**: Found a solution, in case anyone else runs into this problem. Go to "Software and Updates", click on "Additional Drivers" and make sure the the driver is selected (as in the screenshot below)

![use_driver_screenshot](https://user-images.githubusercontent.com/33583345/94346844-fedf5480-001e-11eb-8ab4-9468f0c5fa50.png)

**Comment by brittAnderson** [comment]
Great Sean! Thanks for posting the problem and solution. Since a couple of folks had problems with unetbootin and persistence I was wondering if you had any tips to share? If so, probably best to do as a new issue. Thanks.

**Comment by seanrowe95** [comment]
> Great Sean! Thanks for posting the problem and solution. Since a couple of folks had problems with unetbootin and persistence I was wondering if you had any tips to share? If so, probably best to do as a new issue. Thanks.
> UPDATE: never mind. I just re-read and saw you used rufus -- did you also have unetbootin problems?

@brittAnderson I had tried another service called "balenaEtcher" on my Mac, but that didn't seem to have an option to set the persistence like Rufus does, so I just went with Rufus
