### ISSUE TITLE
Hyper-V not available on Windows 10/11 Home

### ISSUE THREAD

**Issue by ericzhang94** [brittAnderson/Intro2Computing4Psychology#90]
I ran into an issue where I had trouble enabling and installing Hyper-V on Microsoft 11 Home. To see what edition of Windows you have,  check under Windows Specifications in your settings. I managed to get Hyper-V onto my laptop after following the steps on this website: https://www.makeuseof.com/install-hyper-v-windows-11-home/    The website instructs you to run a script into a .bat file, and the program should appear after restarting. Although this method worked for me, I cannot guarantee the same will work for you, so use at your own risk.

**Comment by brittAnderson** [comment]
Thanks Eric. The key is that if you have Windows HOME edition you may need to upgrade to PRO. If you can't do that, Eric found a work around that works for him. But always create a system restore for Windows before you try things like that. In general, always back up and save your important work before system changes on your computer.
