### ISSUE TITLE
Running Ubuntu when it says not enough memory

### ISSUE THREAD

**Issue by wangba12345** [brittAnderson/Intro2Computing4Psychology#91]
Hi, I want to share a tip with everyone about running Ubuntu. Not sure if anyone had experienced the same problem as I did. When I was trying to start the Ubuntu, it says not enough memory. To successfully start Ubuntu, you can just open the settings of Ubuntu on the HyperV manager right page, click on 'memory', and set the allocated memory (RAM and maximum RAM) to Ubuntu a value your device can run with. I set it to 2048 and it ran almost smoothly. But I'm not sure if it will affect future assignments?

-
<img width="536" alt="Ubuntu_Memory" src="https://github.com/brittAnderson/Intro2Computing4Psychology/assets/109424805/214cf908-fd90-4e45-83d0-f9b8639b7aef">

Yueping

**Comment by brittAnderson** [comment]
Thanks for sharing.
