### ISSUE TITLE
Can't connect wirelessly to Wifi in UTM

### ISSUE THREAD

**Issue by achoucro** [brittAnderson/Intro2Computing4Psychology#92]
I am using a Mac M2 and have no idea how to connect to the system to wifi so that I can submit the emacs installation assignment

**Comment by brittAnderson** [comment]
Always helpful to have a little more detail. 
1) Did you successfully install Ubuntu in your VM?
2) Do you have internet functioning of the mac side?
3) Have you successfully downloaded emacs to your vm?
4) Have you tried a shutdown and restart?

Don't panic on the due date. Let us know if these steps have been tried and what worked and what did not.

**Comment by achoucro** [comment]
Hi!
1. Yes Ubuntu is installed 
2. Yes the internet works perfectly on my Mac 
3. Emacs is downloaded and running well
4. I tried to shut down  and restart twice, no luck.

**Comment by brittAnderson** [comment]
I am a bit of a loss. I am typing this to you right now from a Mac Air with the M2 chip running Ventura 13.3.1 and UTM 4.16 and Ubuntu 22.04.2 LTS. I am in the Ubuntu virtual machine and typing on the firefox app running inside ubuntu. I don't have a wifi icon. Did you open a web browser and try going to some random site? If so, what error message do you get? Also, I also don't see similar issues on the internet. How does your software match up to the above.

**Comment by achoucro** [comment]
Hi, I am running from a Mac Air with M2 as well, Ventura 13.3.1 and not sure which UTM version honestly, but Ubuntu 22.04.2 LTS. I am not seeing Firefox inside Ubuntu, and so not have a wifi icon as well. I also cannot find any web browsers. Essentially I tried connecting my email account when I saw I did not have internet access. When I search to wifi settings it says "no Wi-Fi Adapter Found make sure you have wifi adapter plugged and turned on"

**Comment by brittAnderson** [comment]
Firefox is installed as part of Ubuntu. If you installed Ubuntu it is there, and if it is not there your install was not completed fully. By default it floats in the upper left and you have a big flat orange screen. You may just have to bring it to class and let us look at it together with you. If you are worried about the emacs assignment just take the picture with your phone for the moment.

**Comment by achoucro** [comment]
Unfortunately, I am out of town next week and won't be in class. Would it be possible to book a meeting or come to your office? Are your emails back online? or I can also message on teams

**Comment by brittAnderson** [comment]
Going to send you a direct email.
