### ISSUE TITLE
Opening a new file ending with .py in Emacs

### ISSUE THREAD

**Issue by alinawirthx** [brittAnderson/Intro2Computing4Psychology#93]
When I try to open a new file in Emacs that ends in .py it gives me the following error: 

<img width="727" alt="Screenshot 2023-06-08 at 13 20 29" src="https://github.com/brittAnderson/Intro2Computing4Psychology/assets/133157535/00ada4b9-8f94-4e92-85f0-a6c4024aed34">

What does this error mean?

**Comment by brittAnderson** [comment]
Those are warnings not errors. You can ignore them and everything should work. 

We can try to make them go away, but for the moment I think you can just type, no?

You could as a test try to install and enable the optional package pyglet (in emacs using the emacs package system). That might fix things. 

https://github.com/jorgenschaefer/elpy

**Comment by alinawirthx** [comment]
The warnings won't let me type on the file. I do have elpy installed but under status it says "dependency". 

<img width="708" alt="Screenshot 2023-06-08 at 14 03 59" src="https://github.com/brittAnderson/Intro2Computing4Psychology/assets/133157535/0ce21601-8e0b-4917-9f3e-5ee01c11ea0b">

**Comment by brittAnderson** [comment]
Are you sure you can't write in your file? Maybe when the warning comes up the buffer changes to a new one and your old file.py is in the back some where? Did you look for it with C-x C-b?
