### ISSUE TITLE
Creating Source Blocks in Org Mode

### ISSUE THREAD

**Issue by oliviavento** [brittAnderson/Intro2Computing4Psychology#96]
Hi everyone, 
I'm having trouble creating a source code block in org mode. I created my init.el file (pasted below), restarted emacs, opened a new file, and tried to create a source block by typing: 
#+Begin_src python :results function :export both
return(2+2)
#+End_src
but no result came up. 
If anyone can see where I'm going wrong, I'd really appreciate any help/advice! 

Thanks,
Olivia

INIT.EL File
 (require 'package)
(add-to-list 'package-archives '("melpa" ."http://melpa.org/packages/") t)
(package-initialize)

(global-visual-line-mode)

(use-package magit
  :ensure t
  :bind ("C-c m" . magit-status)
  )

(setq org-confirm-babel-evaluate nil)
(setq org-babel-python-command "python3")
  (org-babel-do-load-languages
  'org-babel-load-languages
  '((emacs-lisp . t) 
  (R . t)
  (python . t)))

**Comment by brittAnderson** [comment]
I think you need exports with an s. Here are two mini-files that work for me. Do they work for you?

Actually, it won't let me load them so I put them into the code examples folder under simpleOrgExamples.

**Comment by oliviavento** [comment]
I was able to run the return(2+2) code and get the result, thank you! 

For some reason, the short cut (<s + tab) is not working to get the #+begin_src and #+end_src text, do you know why this might be?

**Comment by brittAnderson** [comment]
I think they changed the short cut to `C-c C-,`

If that doesn't work you can look at the help (`C-h f`) for the function `org-insert-structure-template`. You have to be in an org file for the insert to work. That may mean you have to save the file once to make sure emacs knows it is an org file.

**Comment by oliviavento** [comment]
It worked, thank you very much! 

For anyone else trying to use the shortcut for #+begin_src and #+end_src, it is C-c C-, and then press s to specify src
