### ISSUE TITLE
Learn not allowing to submit .sh files

### ISSUE THREAD

**Issue by c68kim** [brittAnderson/Intro2Computing4Psychology#97]
For terminalShellAssessment, it seems like I cannot submit .sh files on Learn. Or did I miss anything in the instruction?

![Screenshot from 2023-06-21 23-29-19](https://github.com/brittAnderson/Intro2Computing4Psychology/assets/133807865/9cadd278-4a55-4588-8fa3-65418e0da6c0)

**Comment by brittAnderson** [comment]
Yes. This was discussed in class. Because .sh files are executable Learn blocks them. Once you have tested and are ready to upload your file change the .sh part of .txt and up load. I will change it back for testing and grading.

**Comment by c68kim** [comment]
Got it. Thanks!
