### ISSUE TITLE
Unzipping the Practice Data File 

### ISSUE THREAD

**Issue by MollyMatthews** [brittAnderson/Intro2Computing4Psychology#99]
Hello,
Something is going wrong when I am trying to unzip the HSQ practice data file  (from the Data with Python section). Everything including "import zipfile" all seemed to work but when I use this to try to unzip it: 

with zipfile.ZipFile('./HSQ.zip', 'r') as zip_ref: zip_ref.extractall('.')

I get the error "AttributeError: module 'zipfile' has no attribute 'Zipfile'

Does anybody know what this means or anything I should try next?

**Comment by brittAnderson** [comment]
Try using the code formatting (the little <> button) to help make it easier to cut and paste your code for testing. 
Also, you can use the link icon to insert the link to the page where you are getting the code to help shorten the search time for those trying to help you. 

In this case can you confirm that you ran:
    
    import requests
    url = "http://openpsychometrics.org/_rawdata/HSQ.zip"
    r = requests.get(url)
    filename = url.split('/')[-1]
    with open(filename,'wb') as output_file:
        output_file.write(r.content)`

And that it all worked without error. That you can in fact see the file you downloaded in the directory you are working in?

**Comment by MollyMatthews** [comment]
(Sorry still not really sure how issues work) 
Yes, all of that worked without error. I can see the zip file in my directory but not the "unzipped" one. So I guess the importing part worked too. 

What I used: 
```
with zipfile.ZipFile('./HSQ.zip', 'r') as zip_ref:
    zip_ref.extractall('.')
```
Where I got it from: 
[https://brittanderson.github.io/Intro2Computing4Psychology/book/working-with-data-in-python.html](url)

**Comment by brittAnderson** [comment]
You will need to be more specific about "my directory". That `./HSQ.zip` means it will look in the current directory. If you are executing the code in a different directory than you are looking at it may not find it. Try substituting the full path. That means the whole path : `/home/molly/..../HSQ.zip` The ... means I don't really know your file path.

**Comment by MollyMatthews** [comment]
Yes, I am looking in a specific directory. I'm pretty sure I've executed everything in the same directory which is through my desktop and into a folder containing all my psych 363 files. I copied the path from my files to make sure it was in that one. I'm not sure what the "Attribution Error" means. 
I was just doing it in a python interpreter on the side and I saved it as a file, it but it won't let me attach it here for some reason. It says It says I need to save it as a different file type or something.  
I might just keep trying later..

**Comment by SaiTheSaint** [comment]
I hope you have solved this problem, if not, I think it might be due to the lower case 'f' you used in your code.
The zipfile module has the ZipFile class (note the capital 'F'), and it is case sentitive, this code should work:

import zipfile

with zipfile.ZipFile('./HSQ.zip', 'r') as zip_ref:
    zip_ref.extractall('.')

This code should correctly unzip the file 'HSQ.zip' into your current directory.
